### ISSUE TITLE
Team Charter for Team Linked feedback

### ISSUE THREAD

**Issue by nbir012** [dvasques83/medsci736#2]
The charter looks great, I like the .md file type and how you can use headings. It makes everything look really clear (I used a .txt file so my formatting doesn't look as nice as yours - probably because I have no formatting!).

You might like to expand a bit on the project vision as I'm not sure what network visualization is. I guess if an outsider were to look at this team charter they wouldn't know exactly what the project was about. For instance you could do something like this ''Network visualization, a process whereby blah blah blah, to allow for collaboration among top patent developers''. It's still high level but if you got run over by a bus then someone who came in to carry on the project would know exactly what it's about.

Other than that everything looks rad!

Good luck with the project - I'd like to find out more about it next time I see you in class.

**Comment by dvasques83** [comment]
Thanks for your feedback @nbir012.  I appreciate for telling that is not so clear for an outsider. Many times we get so involved in our everyday work that we forget we need to be more explicit when communicating our studies. Cheers.

**Comment by nbir012** [comment]
Cool, looks good. I will close the issue
